global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  
  - job_name: "asguard"
    scrape_interval: 5s
    static_configs:
      - targets: ["192.168.0.2:9182"]
  
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]