global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  
  - job_name: "asguard"
    # scrape_interval: 10s
    static_configs:
      - targets: ["192.168.0.100:9182"]
  
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
  
  - job_name: "nginx"
    static_configs:
      - targets: ["192.168.0.200:9113"]
  
  - job_name: "grafana"
    static_configs:
      - targets: ["192.168.0.200:3000"]
  
  - job_name: "picore"
    static_configs:
      - targets: ["192.168.0.200:9100"]