global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  
  - job_name: "asguard"
    # scrape_interval: 10s
    static_configs:
      - targets: ["asuguard:9182"]
  
  - job_name: "cadvisor"
    static_configs:
      - targets: ["olympus:9102"]
      - targets: ["picore:9102"]
      - targets: ["pi-node-2:9102"]
  
  - job_name: "caddy"
    static_configs:
      - targets: ["picore:2019"]
  
  - job_name: "grafana"
    static_configs:
      - targets: ["olympus:3000"]
  
  - job_name: "loki"
    static_configs:
      - targets: ["loki:3100"]
  
  - job_name: "home-watch"
    static_configs:
      - targets: ["picore:9101"]
  
  - job_name: "system-watch"
    static_configs:
      - targets: ["olympus:9104"]